export const ACHIEVEMENT_CRITERIA_OPERATOR = {
  GTE: 'gte',
  SUM: 'sum',
} as const;

export const ACHIEVEMENT_CRITERIA_OPERATORS = [
  ACHIEVEMENT_CRITERIA_OPERATOR.GTE,
  ACHIEVEMENT_CRITERIA_OPERATOR.SUM,
] as const;

export const DEFAULT_SUM_VALUE_FIELD = 'amount';
export const MAX_ACHIEVEMENT_TARGET = 1_000_000_000;
