export const ACHIEVEMENT_CODE_MAX_LENGTH = 64;
export const ACHIEVEMENT_NAME_MAX_LENGTH = 128;
export const ACHIEVEMENT_DESCRIPTION_MAX_LENGTH = 10_000;
export const ACHIEVEMENT_ICON_MAX_LENGTH = 128;
export const ACHIEVEMENT_MAX_REWARD_POINTS = 1_000_000;
export const ACHIEVEMENT_SORT_ORDER_MIN = -32768;
export const ACHIEVEMENT_SORT_ORDER_MAX = 32767;

export const ADMIN_ACHIEVEMENTS_LIMIT_MIN = 1;
export const ADMIN_ACHIEVEMENTS_LIMIT_MAX = 200;
export const ADMIN_ACHIEVEMENTS_OFFSET_MIN = 0;
export const ADMIN_ACHIEVEMENTS_OFFSET_MAX = 1_000_000;
