export enum AchievementCategory {
  ACHIEVEMENT_CATEGORY_UNSPECIFIED = 0,
  ACHIEVEMENT_CATEGORY_VISITS = 1,
  ACHIEVEMENT_CATEGORY_SPENDING = 2,
  ACHIEVEMENT_CATEGORY_TIER = 3,
  ACHIEVEMENT_CATEGORY_TIME = 4,
  ACHIEVEMENT_CATEGORY_SPECIAL = 5,
  ACHIEVEMENT_CATEGORY_STREAK = 6,
  ACHIEVEMENT_CATEGORY_SECRET = 7,
}

export enum AchievementRarity {
  ACHIEVEMENT_RARITY_UNSPECIFIED = 0,
  ACHIEVEMENT_RARITY_COMMON = 1,
  ACHIEVEMENT_RARITY_UNCOMMON = 2,
  ACHIEVEMENT_RARITY_RARE = 3,
  ACHIEVEMENT_RARITY_EPIC = 4,
  ACHIEVEMENT_RARITY_LEGENDARY = 5,
}

export enum AchievementStrategy {
  ACHIEVEMENT_STRATEGY_UNSPECIFIED = 0,
  ACHIEVEMENT_STRATEGY_INSTANT = 1,
  ACHIEVEMENT_STRATEGY_THRESHOLD = 2,
  ACHIEVEMENT_STRATEGY_STREAK = 3,
}
