export enum PointsTransactionType {
  EARN_TICKET = 'EARN_TICKET',
  EARN_FOOD = 'EARN_FOOD',
  EARN_BIRTHDAY = 'EARN_BIRTHDAY',
  EARN_SPECIAL = 'EARN_SPECIAL',
  EARN_PROMO = 'EARN_PROMO',
  BURN_DISCOUNT = 'BURN_DISCOUNT',
  BURN_REWARD = 'BURN_REWARD',
  EXPIRE = 'EXPIRE',
  ADJUST = 'ADJUST',
  REFUND = 'REFUND',
  EARN_ACHIEVEMENT = 'EARN_ACHIEVEMENT',
}
